# 应用服务 WEB 访问端口
server:
  port: 8083
  servlet:
    session:
      timeout: 600
spring:
  application:
    name: railway_system
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/railway_system?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  redis:
    host: 127.0.0.1
    password: root
    port: 6379
  session:
    store-type: redis
    redis:
      namespace: test:spring:session
mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: graduation.railway_system.mybatis.entity
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
